
docker-build:
    image: ccob/windows_cross:latest
    tags: 
        - docker
    stage: build
    script: 
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=../toolchain/Linux-mingw64.cmake ..
        - cmake --build --target bofs_x64 .
        - cmake --build --target bofs_x86 .
        - cd bofs
        - make install
        - cd ..
        - cmake --build --target bofnet_managed
        - cmake --install .
    artifacts:
        paths:
            - build/dist    
            - managed/BOFNET/bin/Release/*.nupkg
